version: '3.9'

services:
#  db:
#    image: postgres:14-alpine
#    ports:
#      - "5432:5432"
#    volumes:
#      - ~/apps/postgres:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_DB=postgres
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#    networks:
#      - mynetwork

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
    networks:
      - mynetwork

networks:
  mynetwork:
